name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-1.[0-9]+'

jobs:
  # Create Github Release
  release_github:
    name: Release - Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Changlog
        id: changlog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ github.token }}

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{github.ref}}
          body: ${{ steps.changelog.outputs.changes }}


  # Create Curseforge Release
  release_curseforge:
    name: Release - Curseforge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Generate Changlog
        id: changlog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ github.token }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Place Changlog in build directory
        run: |
          echo ${{ steps.changelog.outputs.changelog }} > /fabric/build/doc/changlog.md
          echo ${{ steps.changelog.outputs.changelog }} > /forge/build/doc/changlog.md

      - name: Gradle Build
        run: /bin/sh ./gradlew publishCurseForge -Pcurseforge_api_key=${{ secrets.CURSEFORGE_KEY }}

  # Create Modrinth Release
  release_modrinth:
    name: Release - Modrinth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Generate Changlog
        id: changlog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ github.token }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Build
        run: /bin/sh ./gradlew build

      - name: Place Changlog in build directory
        run: |
          echo ${{ steps.changelog.outputs.changelog }} > /fabric/build/doc/changlog.md
          echo ${{ steps.changelog.outputs.changelog }} > /forge/build/doc/changlog.md

      - name: Modrinth Publish
        run: /bin/sh ./gradlew modrinth -Pmodrinth_api_key=${{ secrets.MODRINTH_KEY }}